name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - { cc: gcc }
          - { cc: clang }
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          echo 'CC=${{ matrix.cc }}' >> $GITHUB_ENV
          echo 'CFLAGS=-Werror -Wall -Wextra -pedantic' >> $GITHUB_ENV
      - name: Configure
        run: cmake . -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DSYSTEMWIDE=yes
      - name: Build
        run: cmake --build .
      - name: Install
        run: sudo make install
